# Generated by Django 6.0.5 on 2026-05-15 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('moeda_preferida', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar Americano ($)'), ('GBP', 'Libra (£)'), ('BRL', 'Real (R$)'), ('JPY', 'Iene (¥)')], default='EUR', max_length=3)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
